messenger4j:
  appSecret: 94fe14ce44442de2655e36ba235014f0
  verifyToken: 35ULKTYCuv
  pageAccessToken: EAAbzNYF1sw4BAMl8RSJANIfP6tHaDfclRcWdmJ5VMGF6GCsKr2ZBcxJXd2ZC4iST6QlFNl78lA7qYvMhG0l1V9WYujbZADktv1cBJ2ZA90vAGZBUXrSb0ifBZCOZBocDJZCWHJvGDENGgYnTZAJMiCeZAAOeb0jgwDMPZCujsRudks8FAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
